name: packhero
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - atk-1.0=2.36.0
  - backcall=0.2.0
  - blas=1.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.3
  - filelock=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gobject-introspection=1.72.0
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - intel-openmp=2023.1.0
  - ipykernel=6.15.0
  - ipython=8.12.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.3.0
  - jpeg=9e
  - jupyter_client=8.2.0
  - jupyter_core=4.12.0
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcurl=8.1.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.9
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=2.8.4
  - ninja=1.12.1
  - ninja-base=1.12.1
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - packaging=23.0
  - pandas=1.5.3
  - pango=1.50.7
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=24.0
  - pixman=0.40.0
  - ply=3.11
  - poppler=22.12.0
  - poppler-data=0.4.11
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pygraphviz=1.9
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.29.0
  - scikit-learn=1.0.2
  - scipy=1.8.1
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tabulate=0.8.10
  - tbb=2021.8.0
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - seaborn
  - pip:
      - ghidra-stubs==11.4
      - graphviz==0.20.3
      - jpype1==1.6.0
      - memory-profiler==0.61.0
      - progress==1.6
      - pyghidra==2.2.0
      - pyqt5-sip==12.11.0
      - r2pipe==1.8.8
